import XCTest
@testable import IKEMEN_Lab

/// Tests for SelectDefGenerator output correctness
final class SelectDefGeneratorTests: XCTestCase {
    
    var tempDirectory: URL!
    
    override func setUp() {
        super.setUp()
        // Create a temp directory for test files
        tempDirectory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try? FileManager.default.createDirectory(at: tempDirectory, withIntermediateDirectories: true)
        
        // Create mock IKEMEN directory structure
        try? FileManager.default.createDirectory(at: tempDirectory.appendingPathComponent("data"), withIntermediateDirectories: true)
        try? FileManager.default.createDirectory(at: tempDirectory.appendingPathComponent("chars/Ryu"), withIntermediateDirectories: true)
        try? FileManager.default.createDirectory(at: tempDirectory.appendingPathComponent("chars/Ken"), withIntermediateDirectories: true)
        try? FileManager.default.createDirectory(at: tempDirectory.appendingPathComponent("stages/Training"), withIntermediateDirectories: true)
        
        // Create mock .def files
        try? "".write(to: tempDirectory.appendingPathComponent("chars/Ryu/Ryu.def"), atomically: true, encoding: .utf8)
        try? "".write(to: tempDirectory.appendingPathComponent("chars/Ken/Ken.def"), atomically: true, encoding: .utf8)
        try? "".write(to: tempDirectory.appendingPathComponent("stages/Training/Training.def"), atomically: true, encoding: .utf8)
    }
    
    override func tearDown() {
        // Clean up temp directory
        try? FileManager.default.removeItem(at: tempDirectory)
        super.tearDown()
    }
    
    // MARK: - Output Format Tests
    
    func testGenerateContainsHeader() {
        // Given
        let collection = Collection(name: "Test Collection")
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then
        XCTAssertTrue(output.contains("; Generated by IKEMEN Lab"))
        XCTAssertTrue(output.contains("; Collection: Test Collection"))
        XCTAssertTrue(output.contains("; DO NOT EDIT"))
    }
    
    func testGenerateContainsRequiredSections() {
        // Given
        let collection = Collection(name: "Test")
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then
        XCTAssertTrue(output.contains("[Characters]"))
        XCTAssertTrue(output.contains("[ExtraStages]"))
        XCTAssertTrue(output.contains("[Options]"))
    }
    
    func testGenerateContainsDefaultOptions() {
        // Given
        let collection = Collection(name: "Test")
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then
        XCTAssertTrue(output.contains("arcade.maxmatches = 6,1,1,0,0,0,0,0,0,0"))
        XCTAssertTrue(output.contains("team.maxmatches = 4,1,1,0,0,0,0,0,0,0"))
    }
    
    // MARK: - Character Entry Tests
    
    func testGenerateCharacterWithExplicitDef() {
        // Given
        var collection = Collection(name: "Test")
        collection.characters = [.character(folder: "Ryu", def: "Ryu_MvC.def")]
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then
        XCTAssertTrue(output.contains("Ryu/Ryu_MvC.def"))
    }
    
    func testGenerateCharacterFindsDefFile() {
        // Given - Ryu.def exists in chars/Ryu/
        var collection = Collection(name: "Test")
        collection.characters = [.character(folder: "Ryu")]  // No explicit def
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then - Should find Ryu.def automatically
        XCTAssertTrue(output.contains("Ryu/Ryu.def"))
    }
    
    func testGenerateCharacterFallbackToFolderName() {
        // Given - No .def file exists for this character (folder doesn't exist)
        var collection = Collection(name: "Test")
        collection.characters = [.character(folder: "NonExistent")]
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then - Should fallback to folder name
        XCTAssertTrue(output.contains("NonExistent/NonExistent.def"))
    }
    
    func testGenerateMultipleCharacters() {
        // Given
        var collection = Collection(name: "Test")
        collection.characters = [
            .character(folder: "Ryu", def: "Ryu.def"),
            .character(folder: "Ken", def: "Ken.def")
        ]
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then
        XCTAssertTrue(output.contains("Ryu/Ryu.def"))
        XCTAssertTrue(output.contains("Ken/Ken.def"))
        
        // Verify order (Ryu should come before Ken)
        let ryuRange = output.range(of: "Ryu/Ryu.def")!
        let kenRange = output.range(of: "Ken/Ken.def")!
        XCTAssertTrue(ryuRange.lowerBound < kenRange.lowerBound)
    }
    
    // MARK: - Special Entry Tests
    
    func testGenerateRandomSelect() {
        // Given
        var collection = Collection(name: "Test")
        collection.characters = [
            .character(folder: "Ryu", def: "Ryu.def"),
            .randomSelect(),
            .character(folder: "Ken", def: "Ken.def")
        ]
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then
        XCTAssertTrue(output.contains("randomselect"))
    }
    
    func testGenerateEmptySlot() {
        // Given
        var collection = Collection(name: "Test")
        collection.characters = [
            .character(folder: "Ryu", def: "Ryu.def"),
            .emptySlot(),
            .character(folder: "Ken", def: "Ken.def")
        ]
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        let lines = output.components(separatedBy: "\n")
        
        // Then - Find the [Characters] section and verify there's an empty line between Ryu and Ken
        let ryuIndex = lines.firstIndex { $0.contains("Ryu/Ryu.def") }!
        let kenIndex = lines.firstIndex { $0.contains("Ken/Ken.def") }!
        
        // There should be an empty line between Ryu and Ken
        XCTAssertEqual(kenIndex - ryuIndex, 2, "Expected one empty line between Ryu and Ken")
        XCTAssertTrue(lines[ryuIndex + 1].isEmpty, "Expected empty line after Ryu")
    }
    
    func testGenerateMixedEntryTypes() {
        // Given - A realistic roster with all entry types
        var collection = Collection(name: "MvC2")
        collection.characters = [
            .character(folder: "Ryu", def: "Ryu.def"),
            .character(folder: "Ken", def: "Ken.def"),
            .emptySlot(),
            .randomSelect(),
            .emptySlot()
        ]
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then
        XCTAssertTrue(output.contains("Ryu/Ryu.def"))
        XCTAssertTrue(output.contains("Ken/Ken.def"))
        XCTAssertTrue(output.contains("randomselect"))
    }
    
    // MARK: - Stage Tests
    
    func testGenerateStages() {
        // Given
        var collection = Collection(name: "Test")
        collection.stages = ["Training"]
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then
        XCTAssertTrue(output.contains("stages/Training/Training.def"))
    }
    
    func testGenerateMultipleStages() {
        // Given
        var collection = Collection(name: "Test")
        collection.stages = ["Training", "Bifrost"]
        
        // Create Bifrost stage folder
        try? FileManager.default.createDirectory(at: tempDirectory.appendingPathComponent("stages/Bifrost"), withIntermediateDirectories: true)
        try? "".write(to: tempDirectory.appendingPathComponent("stages/Bifrost/Bifrost.def"), atomically: true, encoding: .utf8)
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then
        XCTAssertTrue(output.contains("stages/Training/Training.def"))
        XCTAssertTrue(output.contains("stages/Bifrost/Bifrost.def"))
    }
    
    // MARK: - Write Tests
    
    func testWriteSelectDefCreatesFile() {
        // Given
        var collection = Collection(name: "Test")
        collection.characters = [.character(folder: "Ryu", def: "Ryu.def")]
        
        // When
        let result = SelectDefGenerator.writeSelectDef(for: collection, ikemenPath: tempDirectory)
        
        // Then
        switch result {
        case .success(let path):
            XCTAssertTrue(FileManager.default.fileExists(atPath: path.path))
            XCTAssertEqual(path.lastPathComponent, "select.def")
        case .failure(let error):
            XCTFail("Expected success, got error: \(error)")
        }
    }
    
    func testWriteSelectDefCreatesBackup() {
        // Given - Create an existing select.def
        let existingContent = "; Existing select.def"
        let selectDefPath = tempDirectory.appendingPathComponent("data/select.def")
        try? existingContent.write(to: selectDefPath, atomically: true, encoding: .utf8)
        
        let collection = Collection(name: "Test")
        
        // When
        let _ = SelectDefGenerator.writeSelectDef(for: collection, ikemenPath: tempDirectory)
        
        // Then - A backup file should exist
        let dataDir = tempDirectory.appendingPathComponent("data")
        let files = try? FileManager.default.contentsOfDirectory(at: dataDir, includingPropertiesForKeys: nil)
        let backupFiles = files?.filter { $0.lastPathComponent.hasPrefix("select.def.backup.") } ?? []
        
        XCTAssertFalse(backupFiles.isEmpty, "Expected at least one backup file")
    }
    
    func testWriteSelectDefPreservesOriginalInBackup() {
        // Given - Create an existing select.def with specific content
        let existingContent = "; Original content"
        let selectDefPath = tempDirectory.appendingPathComponent("data/select.def")
        try? existingContent.write(to: selectDefPath, atomically: true, encoding: .utf8)
        
        let collection = Collection(name: "Test")
        
        // When
        let _ = SelectDefGenerator.writeSelectDef(for: collection, ikemenPath: tempDirectory)
        
        // Then - Backup should contain original content
        let dataDir = tempDirectory.appendingPathComponent("data")
        let files = try? FileManager.default.contentsOfDirectory(at: dataDir, includingPropertiesForKeys: nil)
        let backupFile = files?.first { $0.lastPathComponent.hasPrefix("select.def.backup.") }
        
        if let backupFile = backupFile {
            let backupContent = try? String(contentsOf: backupFile, encoding: .utf8)
            XCTAssertEqual(backupContent, existingContent)
        } else {
            XCTFail("No backup file found")
        }
    }
    
    // MARK: - Edge Cases
    
    func testGenerateEmptyCollection() {
        // Given
        let collection = Collection(name: "Empty")
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then - Should still have valid structure
        XCTAssertTrue(output.contains("[Characters]"))
        XCTAssertTrue(output.contains("[ExtraStages]"))
        XCTAssertTrue(output.contains("[Options]"))
    }
    
    func testGenerateCollectionWithSpecialCharactersInName() {
        // Given
        let collection = Collection(name: "Marvel vs. Capcom 2 — Ultimate")
        
        // When
        let output = SelectDefGenerator.generate(from: collection, ikemenPath: tempDirectory)
        
        // Then
        XCTAssertTrue(output.contains("; Collection: Marvel vs. Capcom 2 — Ultimate"))
    }
}
